# permissions for end users to view groupsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupsync-viewer-role
rules:
- apiGroups:
  - github.oddbit.com
  resources:
  - groupsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.oddbit.com
  resources:
  - groupsyncs/status
  verbs:
  - get
