---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - patch
  - update
  - watch
